language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install -e .
  - pip install -r requirements-travisci.txt Django==$DJANGO
script:
  - python friendship/tests/runtests.py
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5
  - DJANGO=1.5.4
