language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install -e .
  - pip install $DJANGO
  - pip install -r requirements-travisci.txt
script:
  - python friendship/tests/runtests.py
env:
  - DJANGO="Django==1.4.13"
  - DJANGO="Django==1.5.8"
  - DJANGO="Django==1.6.5"
  - DJANGO="https://www.djangoproject.com/m/releases/1.7/Django-1.7b4.tar.gz#egg=django"

matrix:
  exclude:
    # Python 2.6 support has been dropped in Django 1.7
    - python: "2.6"
      env: DJANGO="https://www.djangoproject.com/m/releases/1.7/Django-1.7b4.tar.gz#egg=django"
