language: python
install:
  - pip install tox
  - pip install -r requirements.txt --use-mirrors
before_script:
- "pip install ."
python:
  - "2.7"
virtualenv:
  system_site_packages: true
script: tox
