language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

install:
  - pip install -e .
  - pip install $DJANGO
  - pip install -r requirements-travisci.txt
  - if [[ $TRAVIS_PYTHON_VERSION != '3.3']]; then pip install wsgiref==0.1.2; fi
script:
  - python friendship/tests/runtests.py
env:
  - DJANGO="Django==1.4.12"
  - DJANGO="Django==1.5"
  - DJANGO="Django==1.5.7"
  - DJANGO="Django==1.6.4"
  - DJANGO="Django==1.7"

matrix:
  exclude:
    # Python 2.6 support has been dropped in Django 1.7
    - python: "2.6"
      env: DJANGO="Django==1.7"
